#!/bin/bash

DIR=$(readlink -f $(dirname -- "$0"))

export CGO_ENABLED=1
if test -z "$DEBUG_CGO"
then
  export CC=gcc-13
  export CXX=g++-13
else
  export CC=$DIR/gcc-13.debug
  export CXX=$DIR/g++-13.debug
fi
go clean -cache
if test -n "$EMVP_USE_CUDA"
then
  export CGO_CPPFLAGS="-DUSE_FAST_CODE_WITH_CUDA $EXTRA_CGO_CPPFLAGS"
  # add flags for compile-only with debug: -c -gcflags="all=-N -l" -ldflags="-linkmode=external -extldflags=-Wl,-E"
  export CGO_FLAGS="$CGO_FLAGS  -tags=cuda"
fi

if test -n "$EMVP_RUN_SINGLE"
then
  time go test $CGO_FLAGS ./...
else
  time go test $CGO_FLAGS -bench='^$' ./mvp # not ./... since ./pir is not covered
  for b in BenchmarkCleartextServerExecution BenchmarkRingSLSNEncoding BenchmarkRingSLSNQuery BenchmarkSLSNGenerateTDM BenchmarkSLSNEncoding BenchmarkSLSNQuery BenchmarkSLSNAnswer BenchmarkSLSNDecode
  do
    time go test $CGO_FLAGS -bench=$b -run='^$' ./mvp # not ./... since ./pir is not covered
  done
fi
