#!/bin/bash

DIR=$(readlink -f $(dirname -- "$0"))

export CGO_ENABLED=1
if test -z "$DEBUG_CGO"
then
  export CC=gcc-13
  export CXX=g++-13
else
  export CC=$DIR/gcc-13.debug
  export CXX=$DIR/g++-13.debug
fi
if test -z "$EMVP_USE_CUDA"
then
  exec time go test $CGO_FLAGS -bench=. ./...
else
  export CGO_CPPFLAGS="-DUSE_FAST_CODE_WITH_CUDA"
  # add flags for compile-only with debug: -c -gcflags="all=-N -l" -ldflags="-linkmode=external -extldflags=-Wl,-E"
  exec time go test $CGO_FLAGS -tags=cuda -bench=. ./...
fi
