#!/bin/bash

set -e

if [[ "$(uname)" == "Darwin" ]]; then
    export CGO_LDFLAGS="-L$(brew --prefix openssl@3)/lib"
    export CGO_CFLAGS="-I$(brew --prefix openssl@3)/include"
    export CGO_CXXFLAGS="-I$(brew --prefix openssl@3)/include"
    echo "[Info] Using OpenSSL from $(brew --prefix openssl@3)"
fi

# Prefer GCC 17 if available, otherwise fallback to g++
if command -v g++-17 >/dev/null 2>&1; then
    CXX=g++-17
elif command -v g++-13 >/dev/null 2>&1; then
    CXX=g++-13
elif command -v clang++ >/dev/null 2>&1; then
    CXX=clang++
else
    CXX=g++
fi

NVCC=nvcc

ARCH=$(uname -m)

if [ "$ARCH" = "x86_64" ]; then
    SIMD_FLAGS="-maes -msse -msse2 -mavx2"
else
    # Apple Silicon (arm64): use NEON instead of x86 SIMD
    SIMD_FLAGS=""
fi

if test -n "$EMVP_USE_CUDA"
then
  EXTRA_CXX_FLAGS="$EXTRA_CXX_FLAGS -DUSE_FAST_CODE_WITH_CUDA"
fi

COMMONFLAGS="-std=c++17 -I/opt/homebrew/include"
CXXFLAGS="$CXXFLAGS $COMMONFLAGS -march=native $SIMD_FLAGS $EXTRA_CXX_FLAGS"
NVCCFLAGS="$NVCCFLAGS $COMMONFLAGS --expt-relaxed-constexpr -rdc=true -Xcompiler -fPIC $EXTRA_CXX_FLAGS $EXTRA_NVCC_FLAGS"

CGO_CFLAGS="$CGO_CFLAGS $EXTRA_CGO_CFLAGS"
CGO_CXXFLAGS="$CGO_CXXFLAGS $EXTRA_CXXGO_CFLAGS"

CUOBJS=()

function makelib() {
  dir="$1"; shift
  lib="$1"; shift
  objs=()
  cuobjs=()
  for name in "$@"
  do
    ext="${name##*.}"
    base="${name%.*}"
    if [ "$ext" = "cpp" ]
    then
      if [ "$dir/$name" -nt "$dir/$base.o" ]
      then
        (set -x; $CXX $CXXFLAGS -c "$dir/$name" -o "$dir/$base.o")
      fi
      objs+=("$dir/$base.o")
    elif [ "$ext" = "cu" -a -n "$EMVP_USE_CUDA" ]
    then
      if [ "$dir/$name" -nt "$dir/$base.o" ]
      then
        (set -x; $NVCC $NVCCFLAGS -c "$dir/$name" -o "$dir/$base.o")
      fi
      cuobjs+=("$dir/$base.o")
    fi
  done
  if [ -n "$cuobjs" ]
  then
    CUOBJS+=("${cuobjs[@]}")
  fi
  (set -x; ar rcs "$dir/lib$lib.a" "${objs[@]}" "${cuobjs[@]}")
}

makelib dataobjects dataobjects common.cpp docontext.cpp fields.cpp plainfields.cpp matrices.cpp plainmatrices.cpp cudacommon.cu cudaobj.cu cudafields.cu cudamatrices.cu cudagraph.cu

makelib tdm NTT NTT.cpp tdm.cpp plainntt.cpp plaintdm.cpp cudantt.cu cudatdm.cu

makelib mvp MVP mvp.cpp plainmvp.cpp matrixShapeTransform.cpp plainMST.cpp lpn.cpp plainlpn.cpp cudamvp.cu cudaMST.cu cudalpn.cu

makelib ecc ReedSolomon ReedSolomon.cpp plainRS.cpp cudaRS.cu

makelib utils utils rnd_api.cpp testutils.cpp plainrnd.cpp plaintestutils.cpp cudarnd.cu cudatestutils.cu

if [ -n "$CUOBJS" ]
then
  (set -x; $NVCC -dlink "${CUOBJS[@]}" -o "cuda_devlink.o" -lcudart -lcudadevrt)
fi
