#!/bin/bash

if [[ "$(uname)" == "Darwin" ]]; then
    export CGO_LDFLAGS="-L$(brew --prefix openssl@3)/lib"
    export CGO_CFLAGS="-I$(brew --prefix openssl@3)/include"
    echo "[Info] Using OpenSSL from $(brew --prefix openssl@3)"
fi

# Prefer GCC 17 if available, otherwise fallback to g++
if command -v g++-17 >/dev/null 2>&1; then
    CXX=g++-17
elif command -v g++-13 >/dev/null 2>&1; then
    CXX=g++-13
elif command -v clang++ >/dev/null 2>&1; then
    CXX=clang++
else
    CXX=g++
fi

NVCC=nvcc

ARCH=$(uname -m)

if [ "$ARCH" = "x86_64" ]; then
    SIMD_FLAGS="-maes -msse -msse2 -mavx2"
else
    # Apple Silicon (arm64): use NEON instead of x86 SIMD
    SIMD_FLAGS=""
fi

if test -z "$EMVP_USE_CUDA"
then
  EXTRA_CXX_FLAGS=
else
  EXTRA_CXX_FLAGS=-DUSE_FAST_CODE_WITH_CUDA
fi

COMMONFLAGS="-std=c++17 -O3 -I/opt/homebrew/include"
CXXFLAGS="$CXXFLAGS $COMMONFLAGS -march=native $SIMD_FLAGS $EXTRA_CXX_FLAGS"
NVCCFLAGS="$NVCCFLAGS $COMMONFLAGS --expt-relaxed-constexpr -rdc=true -lcudart $EXTRA_CXX_FLAGS"

$CXX $CXXFLAGS -c dataobjects/fields.cpp -o dataobjects/fields.o 
$CXX $CXXFLAGS -c dataobjects/matrices.cpp -o dataobjects/matrices.o 
if test -z "$EMVP_USE_CUDA"
then
  ar rcs dataobjects/libdataobjects.a dataobjects/fields.o
else
  $NVCC $NVCCFLAGS -c dataobjects/cudafields.cu -o dataobjects/cudafields.o 
  $NVCC $NVCCFLAGS -c dataobjects/cudamatrices.cu -o dataobjects/cudamatrices.o 
  $NVCC $NVCCFLAGS -c dataobjects/cudacontext.cu -o dataobjects/cudacontext.o 
  ar rcs dataobjects/libdataobjects.a dataobjects/fields.o dataobjects/cudafields.o dataobjects/cudacontext.o
fi

$CXX $CXXFLAGS -c tdm/NTT.cpp -o tdm/NTT.o 
ar rcs tdm/libNTT.a tdm/NTT.o

$CXX $CXXFLAGS -c mvp/mvp.cpp -o mvp/mvp.o 
$CXX $CXXFLAGS -c mvp/matrixShapeTransform.cpp -o mvp/matrixShapeTransform.o 
ar rcs mvp/libMVP.a mvp/mvp.o mvp/matrixShapeTransform.o

$CXX $CXXFLAGS -c ecc/ReedSolomon.cpp -o ecc/ReedSolomon.o 
ar rcs ecc/libReedSolomon.a ecc/ReedSolomon.o

$CXX $CXXFLAGS -c utils/rnd_api.cpp -o utils/rnd_api.o 
if test -z "$EMVP_USE_CUDA"
then
  $CXX $CXXFLAGS -c utils/plainrnd.cpp -o utils/plainrnd.o 
  ar rcs utils/libutils.a utils/rnd_api.o utils/plainrnd.o
else
  $NVCC $NVCCFLAGS -c utils/cudarnd.cu -o utils/cudarnd.o 
  ar rcs utils/libutils.a utils/rnd_api.o utils/cudarnd.o
fi
